swagger: "2.0"
info:
  title: My Social API
  description: API description docs
  version: 1.0.0
  contact:
    email: hungthuan.dev@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
host: http://localhost:3000
basePath: /api/v1

schemes:
  - "http"

tags:
  - name: Auth
    description: Authentication APIs
  - name: Chats
    description: Chats APIs
  - name: Groups
    description: Groups APIs
  - name: Posts"
    description: Posts APIs
  - name: "Profile"
    description: "Profile APIs"
  - name: "Users"
    description: "User APIs"

paths:
  /auth:
    post:
      tags:
        - "Auth"
      summary: "Login API and get token"
      description: "Input email and password"
      operationId: "login"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Login for user"
          required: true
          schema:
            $ref: "#/definitions/LoginDTO"
      responses:
        "400":
          description: "Invalid input"
        "200":
          description: "Login success"
definitions:
  LoginDTO:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
